# Workspace packages
packages:
  - 'apps/*'
  - 'packages/*'

# Enforce Node and pnpm versions specified in `engines` field of `package.json`
engineStrict: true

# Use whichever pnpm version is available in the environment
pmOnFail: ignore

# Manage peer dependencies explicitly and predictibly
strictPeerDependencies: true
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

# Approve specific build scripts
allowBuilds:
  cypress: true
  esbuild: true

# Relax minimum release age protection for owned packages
minimumReleaseAgeExclude:
  - '@h5web/*'
  - '@esrf/eslint-config'

# Save exact dependency versions in `package.json`
savePrefix: ''

# Every project must have these scripts in their `package.json`
requiredScripts:
  - 'lint:eslint'
  - 'lint:tsc'
