# Workspace packages
packages:
  - 'apps/*'
  - 'packages/*'

# Enforce Node and pnpm versions specified in `engines` field of `package.json`
engineStrict: true

# Use whichever pnpm version is available in the environment
managePackageManagerVersions: false

# Hoist `@types` packages to root `node_modules` to fix type error in linting config
# https://github.com/silx-kit/h5web/pull/1787
publicHoistPattern:
  - '@types/*'

# Manage peer dependencies explicitly and predictibly
strictPeerDependencies: true
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

peerDependencyRules:
  allowedVersions:
    'react-slider>react': '19'

# Fail install if any dependency has unreviewed build scripts
strictDepBuilds: true
onlyBuiltDependencies:
  - '@swc/core'
  - 'cypress'
  - 'esbuild'

# Save exact dependency versions in `package.json`
savePrefix: ''

# Check that `node_modules` is up to date before running scripts
# verifyDepsBeforeRun: 'error'

# Every project must have these scripts in their `package.json`
requiredScripts:
  - 'lint:eslint'
  - 'lint:tsc'
