# Workspace packages
packages:
  - 'apps/*'
  - 'packages/*'

# Enforce Node and pnpm versions specified in `engines` field of `package.json`
engineStrict: true

# Use whichever pnpm version is available in the environment
managePackageManagerVersions: false

# Manage peer dependencies explicitly and predictibly
strictPeerDependencies: true
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

# Fail install if any dependency has unapproved build scripts
strictDepBuilds: true
allowBuilds:
  cypress: true
  esbuild: true

# Save exact dependency versions in `package.json`
savePrefix: ''

# Only install packages that are at least 2 days old
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@h5web/*'
  - '@esrf/config'

# Run install automatically if anything is out of date before running a script
verifyDepsBeforeRun: 'install'

# Every project must have these scripts in their `package.json`
requiredScripts:
  - 'lint:eslint'
  - 'lint:tsc'
