name: Approve snapshots

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: read

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.issue.pull_request && github.event.comment.body == '/approve'

    concurrency:
      # One run at a time per PR (for `issue_comment` events) or branch name (for `workflow_dispatch`)
      group: approve-snapshots_${{ github.event.issue.number || github.ref_name }}
      cancel-in-progress: true

    container:
      # Run in Playwright Docker container for stable visual regression tests
      image: mcr.microsoft.com/playwright:v1.58.2-noble
      options: --user 1001

    steps:
      - name: Get branch name for PR 🔍
        if: github.event_name == 'issue_comment'
        uses: andrevalentin/get-branch-name-by-pr@v1
        id: getBranchName
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-id: ${{ github.event.issue.number }}

      - name: Checkout 🏷️
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.getBranchName.outputs.branch || github.event.ref }}

      - name: Install ⚙️
        uses: ./.github/actions/install

      - name: Build packages 📦
        run: pnpm packages

      - name: Build demo 🛠️
        run: pnpm build

      - name: Serve ⚡️
        run: pnpm serve & pnpm wait-on http://localhost:5173 -t 1m

      - name: Run Cypress 🌳
        run: pnpm cypress:run --env updateSnapshots=true --expose takeSnapshots=true

      - name: Upload debug screenshots and diffs on failure 🖼️
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress
          path: |
            cypress/debug/
            cypress/snapshots/**/__diff_output__/
            cypress/snapshots/**/__received_output__/

      - name: Open PR to update reference snapshots 🎁
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.USER_TOKEN }}
          branch: update-snapshots
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> # https://github.com/peter-evans/create-pull-request/blob/v8/action.yml#L27
          title: 'Update Cypress reference snapshots'
          commit-message: 'Update Cypress reference snapshots'
