name: Deploy Storybook

on:
  workflow_dispatch:
  push:
    tags:
      - v*
      - '!v*-beta.*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v6

      - name: Install ⚙️
        uses: ./.github/actions/install

      - name: Build Storybook 🛠️
        run: pnpm build:storybook

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'apps/storybook/build'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy Storybook 🚀
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
