name: Publish packages

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v6

      - name: Match tag to package version 🧐
        id: packageVersion
        uses: geritol/match-tag-to-package-version@0.2.0
        with:
          TAG_PREFIX: v

      - name: Install ⚙️
        uses: ./.github/actions/install

      - name: Build packages 📦
        run: pnpm packages

      - name: Publish packages 🥳
        run: pnpm -r publish --access public --no-git-checks --tag $NPM_TAG
        env:
          NPM_TAG: "${{ contains(steps.packageVersion.outputs.PACKAGE_VERSION, 'beta') && 'next' || 'latest' }}"
